### 1. Importando a Biblioteca


Por convenção, importamos o Numpy utilizando o alias np.

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
print(f"Versão do Numpy: {np.__version__}")

Versão do Numpy: 2.4.2


### 2. Criando Arrays(Vetores e Matrizes)

In [7]:
# Criando um array 1D (Vetor) a partir de uma lista Pyton
vetor = np.array([1, 2, 3, 4, 5])
print("Vetor 1D:", vetor)

# Criando um array 2D (Matriz) a partir de uma lista de listas
matriz = np.array([[1, 2, 3],[4, 5, 6]])
print("\nMatriz 2D:\n", matriz)



Vetor 1D: [1 2 3 4 5]

Matriz 2D:
 [[1 2 3]
 [4 5 6]]


O numpy possui funções nativas para gerar arrays comuns rapidamente, o que é muito útil para inicializar pesos em redes neurais, por exemplo.

In [11]:
# Array de zeros
zeros = np.zeros((2, 3)) # 2 linhas, 3 colunas
print("Zeros:\n", zeros)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#Array de uns
uns = np.ones((3, 3))
print("Uns:\n", uns) 

Uns:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#Array com uma sequência de números (similar ao range() do Python)
sequencia = np.arange(0, 10, 2) # Inicio, Fim(exclusivo), Passo
print("\nSequência(arange):", sequencia)


Sequência(arange): [0 2 4 6 8]


In [14]:
# Valores Linearmente espaçados
espacados = np.linspace(0, 1, 5) # 5 valores entre 0 e 1
print("\nLinspace:", espacados)


Linspace: [0.   0.25 0.5  0.75 1.  ]


### 3. Inspencionando Arrays

In [16]:
print("Formato(shape):", matriz.shape)  #(linhas, colunas)
print("Dimensões(ndim):", matriz.ndim)  #Numeros de dimensões
print("Tamanho total(size):", matriz.size)  # Total de elementos
print("Tipo de dado(dtype):", matriz.dtype)  # Tipos de elementos

Formato(shape): (2, 3)
Dimensões(ndim): 2
Tamanho total(size): 6
Tipo de dado(dtype): int64
